config/routes.rb
Rails.application.routes.draw do
  devise_for :users,
    controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  root to: 'pages#home'
  resources :users, only: [:show, :edit, :update, :destroy] do
    get 'history', to: 'users#history'
  end
  resources :events do
    resources :surveys, only: [ :show, :update ]
    resources :players, only: [ :create, :destroy, :edit, :update ]
  end
  get 'surveys', to: 'surveys#index'
  resources :avatars, only: [ :edit, :update ]
  resources :games, only: [ :index ] do
    get :autocomplete_game_name, :on => :collection
  end
  get 'about', to: 'pages#about'
end

app/models/user.rb
class User < ApplicationRecord

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable, omniauth_providers: [:facebook]

  has_many :surveys, through: :players
  has_one :host, dependent: :destroy
  has_one :avatar
  has_one :badgelist
  has_many :players
  has_many :events, through: :players
  has_many :wins
  has_many :achievements, through: :badgelist
  validates :username, presence: true, :uniqueness => {
    :case_sensitive => false
  }
  before_create :ensure_new
  after_create :initialize_host

  acts_as_mappable :default_units => :kms,
                   :default_formula => :sphere,
                   :distance_field_name => :distance,
                   :lat_column_name => :lat,
                   :lng_column_name => :lng

  # def ip_address
  #   current_sign_in_ip
  # end

  # def geocode_ip
  #   geo = Geokit::Geocoders::MultiGeocoder.geocode(ip_address)
  #   errors.add(:address, "Could not Geocode address") if !geo.success
  #   self.lat, self.lng = geo.lat,geo.lng if geo.success
  # end

  def votes
    result = Survey.where(vote_id:self.id)
    result.nil? ? [] : result
  end

  def wins
    return Event.where(win_id:self.id)
  end

  def surveys!
    self.events.where("datetime < ? AND win_id IS NULL", Time.now).each { |event| event.surveys! }
    return self.reload.surveys
  end


  private
  def ensure_new
    self.level = 1.0
    self.coins = 0
    self.description = "I'm a QuestBoard noob!"
    self.avatar = Avatar.create({gender:0,hair:0,shoes:0,top:0,bottom:0})
  end

  def initialize_host
    Host.create(user_id:self.id)
  end



  def self.find_for_facebook_oauth(auth)
    user_params = auth.slice(:provider, :uid)
    user_params.merge! auth.info.slice(:email, :first_name, :last_name)
    user_params[:facebook_picture_url] = auth.info.image
    user_params[:token] = auth.credentials.token
    user_params[:token_expiry] = Time.at(auth.credentials.expires_at)
    user_params = user_params.to_h

    user = User.find_by(provider: auth.provider, uid: auth.uid)
    user ||= User.find_by(email: auth.info.email) # User did a regular sign up in the past.
    if user
      user_params[:username] = user.username
      user.update(user_params)
    else
      user_params[:username] = user_params["first_name"] + " " + user_params["last_name"]
      user = User.new(user_params)
      user.password = Devise.friendly_token[0,20]  # Fake password for validation
      user.save
    end

    return user
  end

  def self.find_for_database_authentication(warden_conditions)
      conditions = warden_conditions.dup
      if login = conditions.delete(:login)
        where(conditions.to_h).where(["lower(username) = :value OR lower(email) = :value", { :value => login.downcase }]).first
      elsif conditions.has_key?(:username) || conditions.has_key?(:email)
        where(conditions.to_h).first
      end
  end

  def geocode_address
    geo=Geokit::Geocoders::MultiGeocoder.geocode (ip_address)
    errors.add(:address, "Could not Geocode address") if !geo.success
    self.lat, self.lng = geo.lat,geo.lng if geo.success
  end

end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    user = User.find_for_facebook_oauth(request.env['omniauth.auth'])

    if user.persisted?
      sign_in_and_redirect user, event: :authentication
      set_flash_message(:notice, :success, kind: 'Facebook') if is_navigational_format?
    else
      session['devise.facebook_data'] = request.env['omniauth.auth']
      redirect_to new_user_registration_url
    end
  end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  def create
    @user = build_resource # Needed for Merit
    super
  end

  def update
    @user = resource # Needed for Merit
    super
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find(params[:id])
    @user.surveys!
    @events = Player.where(user_id:@user.id)
  end

  def history
    @user = User.find(params[:user_id])
    @events = @user.events.where('datetime < ?', Time.now)
  end

  def edit
    @user = User.find(params[:id])
  end

 def update
    @user = current_user
    @user.update(user_params)
    @user.save
    redirect_to user_path(@user)
 end

 def destroy
    @user = User.find(params[:id])
    @user.destroy
 end

  private

  def user_params
    params.require(:user).permit(:email, :username, :description)
  end

end

app/views/users/_attendingevents.html.erb
<% def current_same?
  current_user == @user
end %>
<% if !@user.events.blank? %>
<!--     <p><%= current_same? ? 'Your' : "#{@user.username}'s" %> attended event stats:</p> -->
    <%# if user has active events %>
    <% if @user.events.where('datetime > ?', Time.now).any? %>
<!--       <p>Upcoming events <%= current_same? ? 'you are' : "#{@user.username} is" %> going to:</p> -->

      <span class="brand-label">Quests I'm Attending:</span>

      <table class="table table-hover table-bordered">
        <thead>
          <tr>
            <th>Date/Time</th>
            <th>Quest Name</th>
            <th>Game Title</th>
            <th>Host</th>
            <th>Players</th>
          </tr>
        </thead>
        <tbody>
          <% @user.events.where('datetime > ? AND host_id != ?', Time.now, @user.host.id).each do |event| %>
          <tr>
            <td><p style="margin-bottom:0px;"><%= event.datetime.strftime("%b %e, %Y @%H:%M") %></p></td>
            <td><%= link_to "#{event.title}", event_path(event) %></td>
            <td><%= event.game.name %></td>
            <td>
              <%= link_to "#{event.host.user.username}", user_path(event.host.user) %>
            </td>
            <td>
              <%= event.players.length %>/<%= event.game.max_players %>
            </td>
          </tr>
          <% end %>
        </tbody>
      </table>

    <% else %>
      <%# If user has no active events %>
      <p><%= current_same? ? "You aren't" : "#{@user.username} isn't" %> attending any upcoming events.</p>
  <% end %>
 <!--  <p>Total events joined: <%= @user.events.length %></p> -->
  <% else %>
    <%# If never played %>
    <p><%= current_same? ? "You haven't" : "#{@user.username} hasn't" %> joined any events yet!</p>
<% end %>

app/views/users/_hostedstats.html.erb
<%# If user hosted at least one event %>
<% def current_same?
  current_user == @user
end %>
<% if !@user.host.events.blank? %>
<!--     <p><%= current_same? ? 'Your' : "#{@user.username}'s" %> hosting stats:</p> -->
    <%# if user has active events %>
    <% if @user.host.events.where('datetime > ?', Time.now).any? %>
<!--       <p>Upcoming events <%= current_same? ? 'you are' : "#{@user.username} is" %> hosting:</p> -->

      <span class="brand-label">Quests I'm Hosting:</span>

      <table class="table table-hover table-bordered">
        <thead>
          <tr>
            <th>Date/Time</th>
            <th>Quest Name</th>
            <th>Game Title</th>
            <th>Players</th>
          </tr>
        </thead>
        <tbody>
          <% @user.host.events.where('datetime > ?', Time.now).each do |event| %>
          <tr>
            <td>
              <p style="margin-bottom:0px;"><%= event.datetime.strftime("%b %e, %Y @%H:%M") %></p>
            </td>
            <td><%= link_to "#{event.title}", event_path(event) %></td>
            <td><%= event.game.name %></td>
            <td>
              <%= event.players.length %>/<%= event.game.max_players %>
            </td>
          </tr>
          <% end %>
        </tbody>
      </table>

    <% else %>
      <%# If user has no active events %>
      <p><%= current_same? ? "You aren't" : "#{@user.username} isn't" %> hosting any events right now.</p>
  <% end %>
  <% else %>
    <%# If never hosted %>
    <p><%= current_same? ? "You haven't" : "#{@user.username} hasn't" %> hosted any games yet!</p>
<% end %>

app/views/users/edit.html.erb
<div class="page-wrapper">
  <div class="container">
    <div class="row">
      <div class="col-sm-12">
        <div class="account-box">
          <div class="main-heading-group">
            <h2>Edit profile</h2>
          </div>

          <div class="account-form-main">
          <%= simple_form_for(@user) do |f| %>
            <%= f.input :username, required: true, autofocus: true %>
            <%= f.input :email, required: true %>
            <%= f.input :description, as: :text, required: true %>
            <%= f.button :submit, "Update" %>
          <% end %>
          </div>

          <div class="account-footer">
            <p>Unhappy? <%= link_to "Cancel my Account.", user_path(@user), data: { confirm: "Are you sure? Once deleted, an account may NEVER be recovered!" }, method: :delete %></p>
            <%= link_to :back, class: "back-link" do %>
              <i class="fa fa-chevron-left" aria-hidden="true"></i> BACK
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/users/history.html.erb
<div class="page-wrapper">
  <div class="container history-index">
    <div class="ribbon-wrapper">
      <div class="main-heading-group mrg-bottom">
        <h1><%= current_user == @user ? 'Your' : "#{@user.username}'s"%> Quest History</h1>
      </div>
    </div>
    <div class="row is-flex">
        <% @events.each do |event| %>
          <div class="col-sm-4">
            <div class="card card-padding">
                <%= link_to "#{event.title.split.map { |i| i.capitalize }.join(' ')}", event_path(event), class: "event-title" %>
                  <span class="game-title"><i class="fa fa-puzzle-piece" aria-hidden="true"></i> <%= event.game.name %> </span>
                <div class="quest-details">
                  <div class="detail-one">
                    <span class="brand-label">Occurred on:</span>
                    <span>
                      <span class="date" style="margin-bottom:0px;"><%= event.datetime.strftime("%b %e, %Y") %></span><span class="time" style="margin-bottom:0px;">@<%= event.datetime.strftime("%H:%M") %></span>
                    </span>
                  </div>
                  <div class="detail-two">
                    <span class="brand-label">Hosted by:</span>
                    <span><%= link_to "#{event.host.user.username}", user_path(event.host.user) %></span>
                  </div>
                </div>

                <%= link_to "See details", event_path(event), class: "btn brand-btn brand-btn-red" %>
            </div>
          </div>
        <% end %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="page-wrapper page-show-wpr profile-wpr">
  <div class="container">
    <div class="row is-flex page-card">

      <div class="col-xs-12 page-show-heading">
        <div class="main-heading-group alt-heading-group">
          <h2><%= @user.username %>'s Profile</h2>
        </div>
      </div>

      <div class="col-sm-6 main-content user-block">

        <div class="player-card">
          <div class="player-block">
            <%# If viewing own profile %>
            <% if current_user == @user %>
              <%= link_to edit_avatar_path(current_user.avatar), class: "av-edit" do %>
                <i class="fa fa-pencil" aria-hidden="true"></i> Edit
              <% end %>
            <% end %>

            <div class="avatar profile-size"
              data-gender="<%= @user.avatar.gender %>"
              data-hair="<%= @user.avatar.hair %>"
              data-top="<%= @user.avatar.top %>"
              data-bottom="<%= @user.avatar.bottom %>"
              data-shoes="<%= @user.avatar.shoes %>"></div>
            <div class="player-info">
              <%= link_to "#{@user.username}", user_path(current_user), class: "player-username" %><br/>
              <span class="player-level">Level <%= @user.level.floor %></span>
              <%# If viewing own profile %>
              <% if current_user == @user %>
                 <span class="coin-count"><%= image_tag("coin.svg") %> <%= @user.coins %></span>
              <% end %>
              <div class="progress">
                <div class="progress-bar progress-bar-info" style="width:<%= (@user.level.modulo(1)*100).to_i %>%"></div>
              </div>
            </div>
          </div>
        </div>

        <%# If viewing own profile %>
        <% if current_user == @user %>
          <%= link_to edit_user_path(current_user), class: "profile-link" do %>
            <i class="fa fa-pencil" aria-hidden="true"></i> Edit your profile
          <% end %>
        <% end %>

        <span class="brand-label">Biography:</span>
        <span><%= @user.description %></span>

      </div>

      <div class="col-sm-6 sub-content">
        <span class="brand-label">Achievements:</span>
        <div class="achievement-block">
          <% if @user.achievements.blank? %>
            <div class="achievement-slot">
              <div data-toggle="tooltip" data-placement="top" title="No achievements yet">
                <%= image_tag "cobweb-01.svg" %>
              </div>
            </div>
            <span style="color: #999;">It's looking empty here. <i class="fa fa-frown-o" aria-hidden="true"></i>

          <% else %>
            <% @user.achievements.each do |achievement| %>
              <div class="achievement-slot">
                <div data-toggle="tooltip" data-placement="top" title="<%= achievement.name %>">
                  <%= image_tag "badges/#{achievement.id}.svg" %>
                </div>
              </div>
            <% end %>
          <% end %>
        </div>

        <div class="quest-stats-header">
          <span class="brand-label">Quest Statistics:</span>

          <%# If viewing own profile %>
          <% if current_user == @user %>
            <% if @user.events.any? %>
              <%= link_to user_history_path(@user) do %>
                <i class="fa fa-history" aria-hidden="true"></i> View full history
              <% end %>
            <% end %>
          <% end %>
        </div>

        <table class="table table-hover table-bordered">
        <thead>
          <tr>
            <th>Type</th>
            <th>#</th>
          </tr>
        </thead>
          <tbody>
            <tr>
              <td>Attended</td>
              <td><%= @user.events.length %></td>
            </tr>
            <tr>
              <td>Wins</td>
              <td><%= @user.wins.length %></td>
            </tr>
            <tr>
              <td>Hosted</td>
              <td><%= @user.host.events.length %></td>
            </tr>
          </tbody>
        </table>

      </div>

    </div>

    <% if current_user == @user %>
    <div class="row is-flex page-card">

      <div class="col-xs-12 page-show-heading">
        <div class="main-heading-group alt-heading-group">
          <h2>Upcoming Quests</h2>
        </div>
      </div>

      <%# If viewing own profile %>
      <div class="col-sm-12 quest-info">
        <div class="row is-flex">
          <div class="col-sm-6">
            <%= render 'attendingevents' %>
          </div>
          <div class="col-sm-6">
            <%= render 'hostedstats' %>
          </div>
        </div>
      </div>
    </div>
    <% end %>

  </div>
</div>

<%= render 'shared/avatar_javascript' %>