config/routes.rb
Rails.application.routes.draw do
  devise_for :users,
    controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  root to: 'pages#home'
  resources :users, only: [:show, :edit, :update, :destroy] do
    get 'history', to: 'users#history'
  end
  resources :events do
    resources :surveys, only: [ :show, :update ]
    resources :players, only: [ :create, :destroy, :edit, :update ]
  end
  get 'surveys', to: 'surveys#index'
  resources :avatars, only: [ :edit, :update ]
  resources :games, only: [ :index ] do
    get :autocomplete_game_name, :on => :collection
  end
  get 'about', to: 'pages#about'
end

app/views/shared/_avatar_javascript.erb
<% content_for(:js) do %>
  <%= javascript_tag do %>
    const avatar = () => {
      $('.avatar').each((i, el) => {
        $(el).html('');

        let gender_svg = "";
        switch ($(el).data('gender')) {
          case 0:
            gender_svg = '<%= image_tag "avatar/gender/0.svg" %>';
            break;
          case 1:
            gender_svg = '<%= image_tag "avatar/gender/1.svg" %>';
            break;
        };

        let hair_svg = "";
        switch ($(el).data('hair')) {
          case 0:
            hair_svg = '<%= image_tag "avatar/hair/0.svg" %>';
            break;
          case 1:
            hair_svg = '<%= image_tag "avatar/hair/1.svg" %>';
            break;
          case 2:
            hair_svg = '<%= image_tag "avatar/hair/2.svg" %>';
            break;
          case 3:
            hair_svg = '<%= image_tag "avatar/hair/3.svg" %>';
            break;
          case 4:
            hair_svg = '<%= image_tag "avatar/hair/4.svg" %>';
            break;
          case 5:
            hair_svg = '<%= image_tag "avatar/hair/5.svg" %>';
            break;
          case 6:
            hair_svg = '<%= image_tag "avatar/hair/6.svg" %>';
            break;
          case 666:
            hair_svg = '<%= image_tag "avatar/admin/james/hair/666.svg" %>';
            break;
          case 123:
            hair_svg = '<%= image_tag "avatar/admin/carla/hair/123.svg" %>';
            break;
          case 444:
            hair_svg = '<%= image_tag "avatar/admin/rose/hair/444.svg" %>';
            break;
          case 719:
            hair_svg = '<%= image_tag "avatar/admin/trevor/hair/719.svg" %>';
            break;
        };

        let top_svg = "";
        switch ($(el).data('top')) {
          case 0:
            top_svg = '<%= image_tag "avatar/top/0.svg" %>';
            break;
          case 1:
            top_svg = '<%= image_tag "avatar/top/1.svg" %>';
            break;
          case 2:
            top_svg = '<%= image_tag "avatar/top/2.svg" %>';
            break;
          case 3:
            top_svg = '<%= image_tag "avatar/top/3.svg" %>';
            break;
          case 4:
            top_svg = '<%= image_tag "avatar/top/4.svg" %>';
            break;
          case 666:
            top_svg = '<%= image_tag "avatar/admin/james/top/666.svg" %>';
            break;
          case 123:
            top_svg = '<%= image_tag "avatar/admin/carla/top/123.svg" %>';
            break;
          case 444:
            top_svg = '<%= image_tag "avatar/admin/rose/top/444.svg" %>';
            break;
          case 719:
            top_svg = '<%= image_tag "avatar/admin/trevor/top/719.svg" %>';
            break;
        }

        let bottom_svg = "";
        switch ($(el).data('bottom')) {
          case 0:
            bottom_svg = '<%= image_tag "avatar/bottom/0.svg" %>';
            break;
          case 1:
            bottom_svg = '<%= image_tag "avatar/bottom/1.svg" %>';
            break;
          case 2:
            bottom_svg = '<%= image_tag "avatar/bottom/2.svg" %>';
            break;
          case 3:
            bottom_svg = '<%= image_tag "avatar/bottom/3.svg" %>';
            break;
          case 4:
            bottom_svg = '<%= image_tag "avatar/bottom/4.svg" %>';
            break;
          case 666:
            bottom_svg = '<%= image_tag "avatar/admin/james/bottom/666.svg" %>';
            break;
          case 123:
            bottom_svg = '<%= image_tag "avatar/admin/carla/bottom/123.svg" %>';
            break;
          case 444:
            bottom_svg = '<%= image_tag "avatar/admin/rose/bottom/444.svg" %>';
            break;
          case 719:
            bottom_svg = '<%= image_tag "avatar/admin/trevor/bottom/719.svg" %>';
            break;
      }

      let shoes_svg = "";
      switch ($(el).data('shoes')) {
        case 0:
          shoes_svg = '<%= image_tag "avatar/shoes/0.svg" %>';
          break;
        case 1:
          shoes_svg = '<%= image_tag "avatar/shoes/1.svg" %>';
          break;
        case 2:
          shoes_svg = '<%= image_tag "avatar/shoes/2.svg" %>';
          break;
        case 666:
          shoes_svg = '<%= image_tag "avatar/admin/james/shoes/666.svg" %>';
          break;
        case 123:
          shoes_svg = '<%= image_tag "avatar/admin/carla/shoes/123.svg" %>';
          break;
        case 444:
          shoes_svg = '<%= image_tag "avatar/admin/rose/shoes/444.svg" %>';
          break;
        case 719:
          shoes_svg = '<%= image_tag "avatar/admin/trevor/shoes/719.svg" %>';
          break;
    }


        const avatar = {
          gender: gender_svg,
          hair: hair_svg,
          top: top_svg,
          bottom: bottom_svg,
          shoes: shoes_svg,
        };

        console.log(avatar);

        for (let type in avatar) {
          if (type === 'gender' || $(el).data(type) > 0) {
            $(el).append(avatar[type]);
          }
        }
      });
    }

    avatar();

    $('.avatar-choice input').change(e => {
      // "avatar[hair]" => "hair"
      const type = $(e.currentTarget).attr('name').split('[')[1].slice(0, -1);
      const value = parseInt($(e.currentTarget).val());
      $('.avatar').data(type, value);
      avatar();
    });

  <% end %>
<% end %>

app/views/shared/_flashes.html.erb
<% if notice %>
  <!-- <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button> -->
    <%# notice %>
 <!--  </div> -->
<% end %>
<% if alert %>
 <!--  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button> -->
    <%# alert %>
 <!--  </div> -->
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-copyright">
    &copy;<%= Time.new.year %>, QuestBoard, All rights reserved.
  </div>
  <div class="footer-links">
    <!-- <a href="#"><i class="fa fa-instagram"></i></a> -->
    <a href="https://www.facebook.com/lewagontokyo/" target="_blank"><i class="fa fa-facebook" aria-hidden="true"></i></a>
    <a href="https://www.lewagon.com/demoday/94/meetboard" target="_blank"><i class="fa fa-info-circle" aria-hidden="true"></i></a>
    <!-- <a href="#"><i class="fa fa-twitter"></i></a> -->
    <a href="/about"><i class="fa fa-hand-spock-o" aria-hidden="true"></i></a>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-questboard-brand" do %>
    <%= image_tag "questboard_logo_small.svg" %>
  <% end %>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

    <% if user_signed_in? %>

      <button class="toggleit">
        <div class="player-info">
        <div class="nav-player">
          <span class="player-level">Level <%= current_user.level.floor %></span>
          <%# If viewing own profile %>
          <% if current_user == current_user %>
             <span class="coin-count"><%= image_tag("coin.svg") %> <%= current_user.coins %></span>
          <% end %>
        </div>
        <div class="progress">
          <div class="progress-bar progress-bar-info" style="width:<%= (current_user.level.modulo(1)*100).to_i %>%">
          </div>
        </div>

        </div>
      </button>

      <!-- Links when logged in -->
      <%#= link_to "Edit User",  edit_user_path(current_user), class: "navbar-wagon-item navbar-wagon-link" %>
      <%#= link_to "Trips", "#", class: "navbar-wagon-item navbar-wagon-link" %>
<!--       <%= link_to "Create Quest", new_event_path, class: "navbar-wagon-item navbar-wagon-link" %> -->
      <%#= link_to "Tasks (<b>#{current_user.surveys.where(attended:false).length}</b>)".html_safe, surveys_path, class: "navbar-wagon-item navbar-wagon-link" %>

      <div class="navbar-wagon-item">
        <div class="dropdown">
          <% if !current_user.surveys.where(attended:false).blank? %>
          <i class="fa fa-globe dropdown-toggle drop-down-globe" data-toggle="dropdown"></i>
            <span class= "notification-icon" drop-down-globe" data-toggle="dropdown"><%= current_user.surveys.where(attended:false).length %></span>
            <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
              <% if !current_user.surveys.blank? %>
                <% current_user.surveys.where(attended:false).each do |survey| %>
                  <li>
                    <%= link_to "#{survey.event.title}", event_survey_path(survey.event, survey) %>
                  </li>
                <% end %>
                <%= link_to "See all Tasks ( #{current_user.surveys.where(attended:false).length} )", surveys_path, class: "navbar-wagon-item navbar-wagon-link" %>
              <% end %>
               <% else %>
                <i class="fa fa-globe dropdown-toggle" data-toggle="dropdown"></i>
                  <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
                    <li class= "task-class">
                    You have no tasks.
                    </li>
                    </i><%= link_to "See all Tasks ( #{current_user.surveys.where(attended:false).length} )", surveys_path, class: "navbar-wagon-item navbar-wagon-link" %>
                  </ul>
              <% end %>
          </ul>
        </div>
      </div>

      <!-- Avatar with dropdown menu -->
      <div class="navbar-wagon-item">
        <div class="dropdown">
           <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <li>
              <%= link_to user_path(current_user) do %>
                <i class="fa fa-user"></i> <%= t(".profile", default: "Profile") %>
              <% end %>
            </li>
<!--             <li>
              <%= link_to root_path do %>
                <i class="fa fa-home"></i>  <%= t(".profile", default: "Home") %>
              <% end %>
            </li> -->
            <li>
               <%= link_to new_event_path, class: "navbar-wagon-item navbar-wagon-link" do %>
                <i class="fa fa-plus-circle" aria-hidden="true"></i> Create Quest
              <% end %>
            </li>
            <li>
              <%= link_to destroy_user_session_path, method: :delete do %>
                <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
              <% end %>
            </li>
          </ul>
        </div>
      </div>
    <% else %>
      <!-- Login link (when logged out) -->
      <%= link_to t(".sign_in", default: "LOGIN"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %> | <%= link_to "SIGN UP", new_user_registration_path, class: "navbar-wagon-item navbar-wagon-link" %>
    <% end %>
  </div>

  <!-- Dropdown list appearing on mobile only -->

</div>

<% if user_signed_in? %>
<div class="page-wrapper page-show-wpr profile-wpr nav-version <%= yield(:nav_style) %>" id="dashboard">
  <div class="container">
    <div class="row is-flex page-card">

      <div class="col-sm-6 main-content user-block">

        <span class="player-label">You</span>
        <div class="player-card">
          <div class="player-block">
            <div class="avatar-wpr">
              <div class="avatar profile-size"
                data-gender="<%= current_user.avatar.gender %>"
                data-hair="<%= current_user.avatar.hair %>"
                data-top="<%= current_user.avatar.top %>"
                data-bottom="<%= current_user.avatar.bottom %>"
                data-shoes="<%= current_user.avatar.shoes %>"></div>
              <%= link_to edit_avatar_path(current_user.avatar), class: "av-edit" do %>
                <i class="fa fa-pencil" aria-hidden="true"></i> Edit
              <% end %>
            </div>

            <div class="player-info">
              <%= link_to "#{current_user.username}", user_path(current_user), class: "player-username" %><br/>
              <span class="player-level">Level <%= current_user.level.floor %></span>
              <%# If viewing own profile %>
              <% if current_user == current_user %>
                 <span class="coin-count"><%= image_tag("coin.svg") %> <%= current_user.coins %></span>
              <% end %>
              <div class="progress">
                <div class="progress-bar progress-bar-info" style="width:<%= (current_user.level.modulo(1)*100).to_i %>%">
                </div>
              </div>
              <span class="xp-amount"><%= (current_user.level.modulo(1)*100).to_i %>/100</span>
            </div>
          </div>
        </div>

      </div>
      <div class="col-sm-6 sub-content">
        <span class="brand-label">Achievements:</span>
        <div class="achievement-block">
          <% if current_user.achievements.blank? %>
            <div class="achievement-slot">
              <div data-toggle="tooltip" data-placement="top" title="No achievements yet">
                <%= image_tag "cobweb-01.svg" %>
              </div>
            </div>
            <span style="color: #999;">It's looking empty here. <i class="fa fa-frown-o" aria-hidden="true"></i></span>

            <p class="intro-help"><i class="fa fa-exclamation-circle" aria-hidden="true"></i> Find and join a <a data-toggle="tooltip" data-placement="top" title="Board game event">quest</a>  <i class="fa fa-long-arrow-right" aria-hidden="true"></i> <a data-toggle="tooltip" data-placement="top" title="Attend the board game event">Go on your quest</a> <i class="fa fa-long-arrow-right" aria-hidden="true"></i> <a data-toggle="tooltip" data-placement="top" title="After the board game event occurs, check your notifications in the navigation bar for quest follow-ups--upon completion, rewards will be distributed to your character">Claim your rewards</a> of <a data-toggle="tooltip" data-placement="top" title="Experience points (XP) are gained when completing a quest (attending a board game event and following up)">experience points</a> and <a data-toggle="tooltip" data-placement="top" title="Coins are a currency earned for completing tasks and quests; coins allow you to purchase items to customize your character">coins</a> <i class="fa fa-long-arrow-right" aria-hidden="true"></i> <a data-toggle="tooltip" data-placement="top" title="Your level increases when you gain experience from completing quests">Level up!</a> <i class="fa fa-level-up" aria-hidden="true"></i></p>
          <% else %>
            <% current_user.achievements.each do |achievement| %>
              <div class="achievement-slot">
                <div data-toggle="tooltip" data-placement="top" title="<%= achievement.name %>">
                  <%= image_tag "badges/#{achievement.id}.svg" %>
                </div>
              </div>
            <% end %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>
<% end %>

<%= render 'shared/avatar_javascript' %>