config/routes.rb
Rails.application.routes.draw do
  devise_for :users,
    controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  root to: 'pages#home'
  resources :users, only: [:show, :edit, :update, :destroy] do
    get 'history', to: 'users#history'
  end
  resources :events do
    resources :surveys, only: [ :show, :update ]
    resources :players, only: [ :create, :destroy, :edit, :update ]
  end
  get 'surveys', to: 'surveys#index'
  resources :avatars, only: [ :edit, :update ]
  resources :games, only: [ :index ] do
    get :autocomplete_game_name, :on => :collection
  end
  get 'about', to: 'pages#about'
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :game
  belongs_to :host
  belongs_to :win, class_name: 'User', optional: true
  has_many :players, dependent: :destroy
  has_many :surveys, through: :players
  validates :game, :title, :address, :description, :datetime, presence: true
  before_validation :geocode_address, :on => :create


  after_create :initialize_event
  before_save :ensure_gamesize, :set_rewards

  acts_as_mappable :default_units => :kms,
                   :default_formula => :sphere,
                   :distance_field_name => :distance,
                   :lat_column_name => :lat,
                   :lng_column_name => :lng

  def add_user(usr)
    if self.players.length < self.game.max_players && !attending?(usr)
      player = Player.create(user:usr,event:self)
      self.players << player
      self.save
      return true
    end
    return false
  end

  def attending?(usr)
    return true if self.players.include?(usr)
    return false
  end

  def surveys!
    if !already_distributed? && past?
      distribute_surveys!
      return self.reload.surveys
    else
      return self.surveys
    end
  end

  def past?
    self.datetime < Time.now ? true : false
  end

  def time=(val)
    @time = val
  end

  def time
    @time
  end

  private

  def initialize_event
    hostplayer = Player.create(user:self.host.user,event:self)
    self.players << hostplayer
  end

  def already_distributed?
    self.surveys != []
  end

  def distribute_surveys!
    self.players.each { |player| player.survey = Survey.new }
  end

  def ensure_gamesize
    correct_players! unless valid_players?
  end

  def set_rewards
    unless self.game.game_length == 0
      modifier = ((self.game.complexity)+((self.game.game_length)/15))
    else
      modifier = self.game.complexity
    end
    pre = 5.5*self.game.complexity*modifier*(((self.game.max_players)*0.1)/0.6)
    self.experience = pre.to_i
    pre = 1.5*self.game.max_players*modifier
    self.coins = pre.to_i
  end

  def valid_players?
    self.players.length <= self.game.max_players ? true : false
  end

  def correct_players!
    self.players = []
    self.players.each { |player| self.players << player if self.players.length < self.game.max_players }
  end


  def geocode_address
    geo=Geokit::Geocoders::MultiGeocoder.geocode (address)
    # remove all this VVV doexn't work
    if !geo.success
      errors.add(:address, "Could not Geocode address")
      self.lat = 0.0
      self.lng = 0.0
      #remove
    end
    self.citycountry = "#{geo.city}, #{geo.country}"
    self.lat, self.lng = geo.lat,geo.lng if geo.success
  end

end

app/controllers/events_controller.rb
class EventsController < ApplicationController

  def index
     @events = Event.all

    if params[:search_loc] != "" && params[:search_date] != "" && params[:search_game] != ""
      @location = params[:search_loc]
      @game = Game.where('name ILIKE ?', "%#{params[:search_game]}%")
      @datetime = Date.strptime(params[:search_date], "%m/%d/%Y")
      @unsorted_events = Event.by_distance(:origin => "#{@location}")
      @events = []
      for event in @unsorted_events
        if event.datetime > @datetime && @game.include?(event.game)
          @events << event
        end
      end

    elsif params[:search_loc] != "" && params[:search_date] != ""
      @location = params[:search_loc]
      @datetime = Date.strptime(params[:search_date], "%m/%d/%Y")
      @unsorted_events = Event.by_distance(:origin => "#{@location}")
      @events = []
      for event in @unsorted_events
        if event.datetime > @datetime
          @events << event
        end
      end

    elsif params[:search_loc] != "" && params[:search_game] != ""
      @location = params[:search_loc]
      @game = Game.where('name ILIKE ?', "%#{params[:search_game]}%")
      @unsorted_events = Event.by_distance(:origin => "#{@location}")
      @events = []
      for event in @unsorted_events
        if @game.include?(event.game)
          @events << event
        end
      end

    elsif params[:search_date] != "" && params[:search_game] != ""
      @game = Game.where('name ILIKE ?', "%#{params[:search_game]}%")
      @datetime = Date.strptime(params[:search_date], "%m/%d/%Y")
      @unsorted_events = Event.where(game: @game)
      @events = []
      for event in @unsorted_events
       if event.datetime > @datetime
          @events << event
        end
      end


    elsif params[:search_loc] != ""
      @location = params[:search_loc]
      @events = Event.by_distance(:origin => "#{@location}").first(10)


    elsif params[:search_date] != ""
      @datetime = Date.strptime(params[:search_date], "%m/%d/%Y")
      @events = []
      Event.all.each do |event|
        if event.datetime > @datetime
          @events << event
        end
      end

    elsif params[:search_game] != ""
      @game = Game.where('name ILIKE ?', "%#{params[:search_game]}%")
      @events = Event.where(game: @game).first(10)

    else
      @events = Event.all.order("created_at DESC").first(15)
    end

  end

  def show
    @event = Event.find(params[:id])
  end

  def new
    @games = Game.all
    @event = Event.new
  end

  def create
    params = {
      title: event_params[:title],
      description: event_params[:description],
      game: Game.where(name: event_params[:game]).first,
      datetime: parse_datetime(event_params),
      host: current_user.host,
      address: event_params[:address],
      coins: 10,
      experience: 100
    }
    @event = Event.create(params)
    if @event.save
      flash[:notice] = "Event successfully listed!"
      redirect_to event_path(@event)
    else
      flash[:alert] = "Invalid information."
      render :new
    end
  end

  def edit
    @games = Game.all
    @event = Event.find(params[:id])
    @game = @event.game.name
    if @event.host != current_user.host
      flash[:alert] = "You don't own this event."
      redirect_to root_path
    end
  end

  def update
    @event = Event.find(params[:id])
    eparams = {
      title: event_params[:title],
      description: event_params[:description],
      game: Game.where(name: event_params[:game]).first,
      datetime: parse_datetime(event_params),
      host: current_user.host,
      address: event_params[:address],
      coins: 10,
      experience: 100
    }

    @event.update(eparams)
    if @event.save
      redirect_to event_path(@event)
    else
      render :edit
    end
  end

  def destroy
    @event = Event.find(params[:id])
    if (@event.datetime + 86400) < Time.now
      flash[:alert] = "You can no longer delete this event."
      redirect_to root_path
    elsif @event.host != current_user.host
      redirect_to root_path
    else
      @event.destroy
      flash[:notice] = "Event deleted."
      redirect_to root_path
    end
  end

  private

  def event_params
    params.require(:event).permit(:title, :description, :game, :address, :datetime, :time)
  end

  def parse_datetime(e_param)
    datepicker = e_param[:datetime]
    mdy_arr = datepicker.split(/\D/) if datepicker.class == String
    mdy_arr = datepicker[0].split(/\D/) if datepicker.class == Array
    m = mdy_arr[0].to_i
    d = mdy_arr[1].to_i
    y = mdy_arr[2].to_i
    time = e_param.values.last(2)
    hour = time[0].to_i
    min = time[1].to_i
    return Time.new(y,m,d,hour,min)
  end

end

app/views/events/_eventdetails.html.erb
<header>
  <span class="quest-date">
    <p class="date-year time" style="margin-bottom:0px;"
%>
      <%= @event.datetime.strftime("%b %e, %Y at %H:%M") %>
    </p>
  </span>
  <h3><%= @event.title.split.map { |i| i.capitalize }.join(' ') %></h3>
  <span class="game-title"><i class="fa fa-puzzle-piece" aria-hidden="true"></i> <%= @event.game.name %></span>
</header>

<div class="quest-content">
  <% unless @event.win.nil? %>
    <span class="brand-label">Quest Winner:</span>
    <span><%= link_to "#{@event.win.username}", user_path(@event.win) %></span>
  <% end %>
  <span class="brand-label">Address:</span>
  <span><%= @event.address %></span>
  <span class="brand-label">Rewards:</span>
  <div class="quest-rewards">
    <div class="reward-slot">
      <%= image_tag("exp.svg") %>
      <span class="reward-amount"><%= @event.experience %></span>
    </div>
    <div class="reward-slot">
      <%= image_tag("coin.svg") %>
      <span class="reward-amount"><%= @event.coins %></span>
    </div>
  </div>
  <span class="brand-label">Description:</span>
  <blockquote class="small-quote">
    <%= @event.description %>
  </blockquote>
  <%= link_to :back, class: "back-link" do %>
    <i class="fa fa-chevron-left" aria-hidden="true"></i> BACK
  <% end %>
</div>

app/views/events/_partydetails.html.erb
<% if current_user == @event.host.user && !@event.past? %>
  <div class="party-links">
    <%= link_to edit_event_path(@event), class: "edit-link" do %>
      <i class="fa fa-pencil" aria-hidden="true"></i> edit event
    <% end %>
    <%= link_to "delete event", event_path(@event), method: :delete, class: "btn brand-btn brand-btn-red", role: "button", data: { confirm: "Really delete this event?" }  %>
  </div>
  <% elsif @event.players.where("user_id = ?", current_user.id).any? && !@event.past? %>
    <%= link_to "Leave quest", event_player_path([@event, current_user]), method: :delete, class: "btn brand-btn brand-btn-red", role: "button", data: { confirm: "Are you sure you want to abandon this quest?" } %>
<% end %>
<% if @event.players.where("user_id = ?", current_user.id).blank? && @event.players.length < @event.game.max_players && !@event.past? %>
  <%= link_to "Join quest", event_players_path([@event, current_user]), method: :post, class: "btn brand-btn brand-btn-red", role: "button" %>
<% end %>
<span class="player-label">Host</span>
<div class="player-card">
  <div class="player-block">
    <div class="avatar show-size"
      data-gender="<%= @event.host.user.avatar.gender %>"
      data-hair="<%= @event.host.user.avatar.hair %>"
      data-top="<%= @event.host.user.avatar.top %>"
      data-bottom="<%= @event.host.user.avatar.bottom %>"
      data-shoes="<%= @event.host.user.avatar.shoes %>"></div>
    <div class="player-info">
      <span class="player-username"><%= link_to "#{@event.host.user.username}", user_path(@event.host.user) %></span>
      <span class="player-level">Level <%= @event.host.user.level.floor %></span>
      <div class="progress">
        <div class="progress-bar progress-bar-info" style="width:<%= (@event.host.user.level.modulo(1)*100).to_i %>%"></div>
      </div>
    </div>
  </div>
</div>
<% if @event.players.where('user_id != ?', @event.host.user.id).any? %>
<span class="player-label">Players (<%= @event.players.count %>/<%= @event.game.max_players %>)</span>
<div class="player-card">
  <div class="row">
    <div class="attendees-card">
    <% @event.players.each do |player|%>
      <% if player.user != @event.host.user %>
          <div class="col-sm-6">
            <div class="player-block">
              <div class="avatar player-size"
                data-gender="<%= player.user.avatar.gender %>"
                data-hair="<%= player.user.avatar.hair %>"
                data-top="<%= player.user.avatar.top %>"
                data-bottom="<%= player.user.avatar.bottom %>"
                data-shoes="<%= player.user.avatar.shoes %>"></div>
              <div class="player-info">
                <span class="player-username"><%= link_to "#{player.user.username}", user_path(player.user) %></span>
                <span class="player-level">Level <%= player.user.level.floor %></span>
                <div class="progress">
                  <div class="progress-bar progress-bar-info" style="width:<%= (player.user.level.modulo(1)*100).to_i %>%"></div>
                </div>
              </div>
            </div>
          </div>
      <% end %>
    <% end %>
    </div>
  </div>
</div>
<% end %>

app/views/events/edit.html.erb
<script src="https://code.jquery.com/jquery-1.12.4.js"></script>
<script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
<script type="text/javascript">
  $(document).ready(function() {
    $('.datepicker').datepicker();
  });
</script>
<script src="https://maps.googleapis.com/maps/api/js?libraries=places&amp;key=AIzaSyDANjx3bosEtIyzJaoWs50Wnt6nt_1rmxU"></script>

<div class="page-wrapper">
  <div class="container">
    <div class="row">
      <div class="col-sm-12">
        <div class="account-box">
          <div class="main-heading-group">
            <h2>Edit quest</h2>
          </div>

          <div class="account-form-main">
            <%= simple_form_for(@event) do |f| %>
              <%= f.input :title %>
              <%= f.input :game, :url => autocomplete_game_name_games_path, :as => :autocomplete%>
              <%= f.input :description, as: :text %>
              <%= f.input :address, input_html: { :class => 'search-location' }%>
              <%= f.input :datetime, data: { provide:'datepicker'}, :input_html => { :value => Time.now } %>
              <%= f.button :submit, "Update" %>
            <% end %>
          </div>

          <div class="account-footer">
            <%= link_to :back do %>
              <i class="fa fa-chevron-left" aria-hidden="true"></i> BACK
            <% end %>
          </div>

        </div>
      </div>
    </div>
  </div>
</div>

app/views/events/index.html.erb
<div class="page-wrapper event-index-page">
    <div class="container">
      <div class="ribbon-wrapper">
        <div class="main-heading-group mrg-bottom">
          <h1>Quests</h1>
        </div>
      </div>
      <div class="row">

        <% if !@events.blank? %>
          <% @events.each do |event| %>
              <div class="col-sm-6 col-md-4">
                <div class="card">
                  <div class="quest-header">
                    <div class="quest-date-box blue-box">
                      <span class="quest-date">
                        <p class="date">
                          <%= event.datetime.strftime("%b %e") %>
                          </p>
                      </span>
                      <span class="quest-time">
                        <p class="time">
                          <%= event.datetime.strftime("%H:%M") %>
                          </p>
                      </span>
                    </div>
                    <div class="quest-top-info">
                      <span class="game-title">
                        <%= event.game.name %>
                      </span>
                      <span class="quest-distance">
                        <i class="fa fa-map-marker" aria-hidden="true"></i>
                        <% if @location != nil %>
                          <%= event.distance_from(@location, :units=>:kms).round(1) %> km away
                        <% else %>
                          <%= event.citycountry %>
                        <% end %>
                      </span>
                    </div>
                  </div>

                  <div class="quest-main">
                    <span class="event-title"><%= event.title.split.map { |i| i.capitalize }.join(' ') %></span>
                    <span class="rewards-title">Rewards</span>

                    <div class="quest-rewards">
                      <div class="reward-slot">
                        <%= image_tag("exp.svg") %>
                        <span class="reward-amount"><%= event.experience %></span>
                      </div>
                      <div class="reward-slot">
                        <%= image_tag("coin.svg") %>
                        <span class="reward-amount"><%= event.coins %></span>
                      </div>
                    </div>
                  </div>

                  <div class="quest-footer">

                    <div class="event-host">
                      <div class="avatar card-size"
                        data-gender="<%= event.host.user.avatar.gender %>"
                        data-hair="<%= event.host.user.avatar.hair %>"
                        data-top="<%= event.host.user.avatar.top %>"
                        data-bottom="<%= event.host.user.avatar.bottom %>"
                        data-shoes="<%= event.host.user.avatar.shoes %>"></div>
                      <span class="host-pin">GM</span>
                    </div>

                    <span class="player-count"><%= event.players.length %>/<%= event.game.max_players %> PLAYERS</span>
                    <%= link_to "See details", event_path(event), class: "btn brand-btn brand-btn-red" %>

                  </div>
                </div>
              </div>
            <% end %>
          <% else %>
            <div class="col-xs-12">
              <p>Sorry, but there are currently no matches for your search.</p>
            </div>
        <% end %>
    </div>
  </div>
</div>
<%= render 'shared/avatar_javascript' %>

<!-- <ul>
  <% if !@events.blank? %>
    <% @events.each do |event| %>
    <li><%= event.title %>
      <%= event.address %>
      <% if @location != nil %>
      <%= event.distance_from(@location, :units=>:kms).round(1) %>km
      <%= event.datetime %>
      <% else @location = "Tokyo Station" %>
      <%= event.datetime %>
      <% end %>
    </li>
    <% end %>
  <% end %>
</ul> -->

app/views/events/new.html.erb
<script src="https://code.jquery.com/jquery-1.12.4.js"></script>
<script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
<link href="http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.5/themes/base/jquery-ui.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript">
  $(document).ready(function() {
    $('.datepicker').datepicker();
  });
</script>
<script src="https://maps.googleapis.com/maps/api/js?libraries=places&amp;key=AIzaSyDANjx3bosEtIyzJaoWs50Wnt6nt_1rmxU"></script>

<div class="page-wrapper">
  <div class="container">
    <div class="row">
      <div class="col-sm-12">
        <div class="account-box">
          <div class="main-heading-group">
            <h2>Create Quest</h2>
          </div>

          <div class="account-form-main">
            <%= simple_form_for(@event) do |f| %>
              <%= f.input :title %>
              <%= f.input :game, :url => autocomplete_game_name_games_path, :as => :autocomplete %>
              <%= f.input :description, as: :text %>
              <%= f.input :address, input_html: { :class => 'search-location' }%>
              <%= f.input :datetime, as: :search, data:{ provide:'datepicker'}, input_html: { value: Date.today.strftime('%m/%d/%Y'), class: "form-control input-size-large datepicker" } %>
              <%= f.time_select :time %>
              <%= f.button :submit, "Create" %>

            <% end %>
          </div>

          <div class="account-footer">
            <%= link_to :back do %>
              <i class="fa fa-chevron-left" aria-hidden="true"></i> BACK
            <% end %>
          </div>

        </div>
      </div>
    </div>
  </div>
</div>

app/views/events/show.html.erb
<div class="page-wrapper event-show-wpr">
  <div class="container">
    <div class="row is-flex page-card">

      <div class="col-xs-12 event-show-heading">
        <div class="main-heading-group">
          <h2>Quest Details</h2>
        </div>
      </div>

      <div class="col-sm-6 quest-show-info">
        <%= render 'eventdetails' %>
      </div>

      <div class="col-sm-6 quest-show-party">
        <%= render 'partydetails' %>
      </div>

    </div>
  </div>
</div>
<%= render 'shared/avatar_javascript' %>