config/routes.rb
Rails.application.routes.draw do
  devise_for :users,
    controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  root to: 'pages#home'
  resources :users, only: [:show, :edit, :update, :destroy] do
    get 'history', to: 'users#history'
  end
  resources :events do
    resources :surveys, only: [ :show, :update ]
    resources :players, only: [ :create, :destroy, :edit, :update ]
  end
  get 'surveys', to: 'surveys#index'
  resources :avatars, only: [ :edit, :update ]
  resources :games, only: [ :index ] do
    get :autocomplete_game_name, :on => :collection
  end
  get 'about', to: 'pages#about'
end

app/views/pages/about.html.erb
<%= image_tag "le_wagon-01.png", :style => "width: 100%;" %>

app/views/pages/home.html.erb
<% provide(:nav_style, "homepage-player-dashboard") %>

  <div id="spinner-overlay">
    <div class="sk-folding-cube">
      <div class="sk-cube1 sk-cube"></div>
      <div class="sk-cube2 sk-cube"></div>
      <div class="sk-cube4 sk-cube"></div>
      <div class="sk-cube3 sk-cube"></div>
    </div>
      <span>Finding quests</span>
  </div>

<div class="hero-wrapper <%= 'hero-wrapper-alt' if user_signed_in? %>">
  <div class="container">
    <div class="row">

      <div class="col-xs-12">

        <div class="main-heading-group">
          <% if user_signed_in? %>
          <div class="intro-wpr intro-wpr-alt">
              <%= image_tag("questboard_mascot_fornow-01.svg") %>
              <div class="intro-text">
                <h2>find a quest</h2>
              </div>
            </div>
          <% else %>
            <div class="intro-wpr">
              <%= image_tag("questboard_mascot_fornow-01.svg") %>
              <div class="intro-text">
                <h1>hello! find a quest</h1>
                <h2>discover board game events around you</h2>
              </div>
            </div>
          <% end %>
        </div>

        <div class="hero-search">
          <%= form_tag(events_path, :method => "get", id: "search-form", class: "center-block") do %>
            <div class="form-group">
              <%= text_field_tag :search_loc, params[:search_loc], placeholder: "where?", class: "search-location form-control input-size-large" %>
              <%= text_field_tag :search_date, params[:search_date], data:{ provide:'datepicker'}, placeholder: "date", class: "form-control input-size-large datepicker", placeholder: "when?" %>
              <%= autocomplete_field_tag :search_game, params[:search_game], autocomplete_game_name_games_path, placeholder: "what game?", class: "form-control input-size-large" %>
              <%= submit_tag "search", :name => nil, class: "btn brand-alt-btn brand-btn-yellow", id: "search-button" %>
            </div>
          <% end %>
        </div>

      </div>

    </div>
  </div>
</div>

<div class="container">
  <div class="row is-flex">
    <div class="col-sm-9 hp-info">
    <% if user_signed_in? %>
      <h3>News</h3>
      <p>Items to purchase for your character are coming soon. This will allow you to spend your hard-earned coins on some loot! We're planning on having different clothes, shoes, and hairstyles. Change up your style, show off your wardrobe, and have fun with customization!</p>
    <% else %>
      <h3>About QuestBoard</h3>
      <p>QuestBoard provides a way for you to organize board game events, meet fellow board gamers, and track your board game statistics/history through your very own customizable character, complete with a leveling system. The more quests (board game events) that you join and complete, the more experience you earn and the higher your level becomes. Not only can you compete while playing the board game, you can also compete with others through QuestBoard by attaining levels, items, and achievements for your character!</p>

      <p>Find and join a <a data-toggle="tooltip" data-placement="top" title="Board game event">quest</a>  <i class="fa fa-long-arrow-right" aria-hidden="true"></i> <a data-toggle="tooltip" data-placement="top" title="Attend the board game event">Go on your quest</a> <i class="fa fa-long-arrow-right" aria-hidden="true"></i> <a data-toggle="tooltip" data-placement="top" title="After the board game event occurs, check your notifications in the navigation bar for quest follow-ups--upon completion, rewards will be distributed to your character">Claim your rewards</a> of <a data-toggle="tooltip" data-placement="top" title="Experience points (XP) are gained when completing a quest (attending a board game event and following up)">experience points</a> and <a data-toggle="tooltip" data-placement="top" title="Coins are a currency earned for completing tasks and quests; coins allow you to purchase items to customize your character">coins</a> <i class="fa fa-long-arrow-right" aria-hidden="true"></i> <a data-toggle="tooltip" data-placement="top" title="Your level increases when you gain experience from completing quests">Level up!</a> <i class="fa fa-level-up" aria-hidden="true"></i></p>
    <% end %>
    </div>

    <div class="col-sm-3 signup-accent">
      <% if user_signed_in? %>
        <span>Are you ready to host your own quest?</span>
        <%= link_to t(".sign_in", default: "create quest"), new_event_path, class: "btn brand-btn brand-btn-red-invert" %>
      <% else %>
        <span>Are you ready to level up? Let's go!</span>
        <%= link_to t(".sign_in", default: "sign up"), new_user_registration_path, class: "btn brand-btn brand-btn-red-invert" %>
      <% end %>
    </div>

  </div>
</div>

<div class="hp-cards-wpr">
  <div class="container">
    <div class="row">
      <div class="col-xs-12">
        <h3>Happening quests</h3>
      </div>

      <% @events.each do |event| %>
        <div class="col-sm-6 col-md-4">
          <div class="card">
            <div class="quest-header">
              <div class="quest-date-box">
                <span class="quest-date">
                  <p class="date" style="margin-bottom:0px;"
%><%= event.datetime.strftime("%b %e") %></p>
                </span>
                <span class="quest-time">
                  <p class="time" style="margin-bottom:0px;"
%><%= event.datetime.strftime("%H:%M") %></p>
                </span>
              </div>
              <div class="quest-top-info">
                <span class="game-title">
                  <%= event.game.name %>
                </span>
                <span class="quest-distance">
                  <i class="fa fa-map-marker" aria-hidden="true"></i>
                  <span style="font-size:12pt;"><%= event.citycountry %></span>
                </span>
              </div>
            </div>

            <div class="quest-main">
              <span class="event-title"><%= event.title.split.map { |i| i.capitalize }.join(' ') %></span>
              <span class="rewards-title">Rewards</span>

              <div class="quest-rewards">
                <div class="reward-slot">
                  <%= image_tag("exp.svg") %>
                  <span class="reward-amount"><%= event.experience %></span>
                </div>
                <div class="reward-slot">
                  <%= image_tag("coin.svg") %>
                  <span class="reward-amount"><%= event.coins %></span>
                </div>
              </div>
            </div>

            <div class="quest-footer">

              <div class="event-host">
                <div class="avatar card-size"
                  data-gender="<%= event.host.user.avatar.gender %>"
                  data-hair="<%= event.host.user.avatar.hair %>"
                  data-top="<%= event.host.user.avatar.top %>"
                  data-bottom="<%= event.host.user.avatar.bottom %>"
                  data-shoes="<%= event.host.user.avatar.shoes %>"></div>
                <span class="host-pin">GM</span>
              </div>

              <span class="player-count"><%= event.players.length %>/<%= event.game.max_players %> PLAYERS</span>
              <%= link_to "See details", event_path(event), class: "btn brand-btn brand-btn-red" %>

            </div>
          </div>
        </div>
      <% end %>

    </div>
  </div>

</div>